"""gitlink — optionally commit a generated bundle to GitHub or Azure DevOps.

Version control is opt-in: configure a provider + repo in the UI and export a
token as GIT_TOKEN. On "Create" the operator can push the generated bundle to a
new branch and open a pull request, so the migration output lands in the
customer's own repo review flow rather than only on local disk.

Auth (token from env, never stored):
  * GitHub        — GIT_TOKEN = a PAT/fine-grained token with `contents` +
                    `pull_requests`. REST v3 (api.github.com).
  * Azure DevOps  — GIT_TOKEN = a PAT; REST via dev.azure.com, Basic auth with
                    an empty username.

This module uses only the Python standard library (urllib) so it adds no deps.
It is deliberately conservative: any failure returns a message rather than
raising, so a git hiccup never blocks the local bundle write.
"""

from __future__ import annotations

import base64
import json
import os
import urllib.error
import urllib.request
from typing import Any, Dict, List


def commit_bundle(provider: str, repo: str, bundle_dir: str,
                  branch: str, commit_message: str) -> Dict[str, Any]:
    """Commit every file under bundle_dir to `repo` on a new `branch`.

    Returns {"ok": bool, "message": str, "url": str|None}.
    """
    token = os.environ.get("GIT_TOKEN", "")
    if not provider:
        return {"ok": False, "message": "No git provider configured."}
    if not token:
        return {"ok": False,
                "message": f"{provider} selected but GIT_TOKEN is not set in the "
                           f"environment — bundle written locally only."}
    files = _collect_files(bundle_dir)
    try:
        if provider == "github":
            return _github_commit(repo, files, branch, commit_message, token)
        if provider == "azure_devops":
            return _azure_commit(repo, files, branch, commit_message, token)
        return {"ok": False, "message": f"Unknown git provider '{provider}'."}
    except (urllib.error.URLError, KeyError, ValueError) as e:
        return {"ok": False, "message": f"git push failed ({provider}): {e}"}


# --------------------------------------------------------------------------- #
def _collect_files(root: str) -> List[Dict[str, str]]:
    out = []
    for dirpath, _dirs, names in os.walk(root):
        for n in names:
            full = os.path.join(dirpath, n)
            rel = os.path.relpath(full, root)
            with open(full, "r", encoding="utf-8") as fh:
                out.append({"path": rel.replace(os.sep, "/"), "content": fh.read()})
    return out


def _req(url: str, method: str, headers: Dict[str, str], body: Any = None):
    data = json.dumps(body).encode() if body is not None else None
    r = urllib.request.Request(url, data=data, method=method, headers=headers)
    with urllib.request.urlopen(r, timeout=30) as resp:
        return json.loads(resp.read().decode() or "{}")


# ---- GitHub (Contents API + PR) ------------------------------------------- #
def _github_commit(repo: str, files, branch, message, token) -> Dict[str, Any]:
    h = {"Authorization": f"Bearer {token}", "Accept": "application/vnd.github+json",
         "Content-Type": "application/json", "User-Agent": "pseudo-domo-mcp"}
    base = f"https://api.github.com/repos/{repo}"
    # default branch head sha
    info = _req(base, "GET", h)
    default = info["default_branch"]
    ref = _req(f"{base}/git/ref/heads/{default}", "GET", h)
    head = ref["object"]["sha"]
    # create branch
    _req(f"{base}/git/refs", "POST", h,
         {"ref": f"refs/heads/{branch}", "sha": head})
    # put each file on the new branch
    for f in files:
        b64 = base64.b64encode(f["content"].encode()).decode()
        _req(f"{base}/contents/{f['path']}", "PUT", h,
             {"message": message, "content": b64, "branch": branch})
    # open PR
    pr = _req(f"{base}/pulls", "POST", h,
              {"title": message, "head": branch, "base": default,
               "body": "Generated by the Pseudo-Domo migration console."})
    return {"ok": True, "message": f"Opened PR #{pr['number']} on {repo}.",
            "url": pr.get("html_url")}


# ---- Azure DevOps (Pushes API + PR) --------------------------------------- #
def _azure_commit(repo: str, files, branch, message, token) -> Dict[str, Any]:
    # repo = org/project/repo
    org, project, repository = repo.split("/", 2)
    auth = base64.b64encode(f":{token}".encode()).decode()
    h = {"Authorization": f"Basic {auth}", "Content-Type": "application/json"}
    base = f"https://dev.azure.com/{org}/{project}/_apis/git/repositories/{repository}"
    api = "?api-version=7.1"
    # find default branch's latest commit
    refs = _req(f"{base}/refs{api}&filter=heads/", "GET", h)
    default_ref = next((r for r in refs["value"] if r["name"].endswith("/main")
                        or r["name"].endswith("/master")), refs["value"][0])
    old_id = default_ref["objectId"]
    changes = [{"changeType": "add",
                "item": {"path": f"/{f['path']}"},
                "newContent": {"content": f["content"], "contentType": "rawtext"}}
               for f in files]
    push = {"refUpdates": [{"name": f"refs/heads/{branch}", "oldObjectId": old_id}],
            "commits": [{"comment": message, "changes": changes}]}
    _req(f"{base}/pushes{api}", "POST", h, push)
    pr = _req(f"{base}/pullrequests{api}", "POST", h,
              {"sourceRefName": f"refs/heads/{branch}",
               "targetRefName": default_ref["name"], "title": message,
               "description": "Generated by the Pseudo-Domo migration console."})
    return {"ok": True,
            "message": f"Opened PR !{pr.get('pullRequestId')} on {repository}.",
            "url": None}
