"""sdp — render a transpiled lineage as a true Lakeflow Declarative Pipeline.

The transpiler emits a plain-SQL medallion (CREATE OR REPLACE VIEW per layer).
That's correct logic, but not *Lakeflow Declarative Pipeline* (a.k.a. DLT / SDP)
syntax. This module re-renders the same medallion as real SDP in the language
the customer prefers:

  SQL     — CREATE OR REFRESH STREAMING TABLE for bronze ingests (Auto Loader
            read_files), MATERIALIZED VIEW for silver/gold transforms, and
            CONSTRAINT ... EXPECT expectations on the gold contract.
  Python  — @dlt.table functions returning DataFrames, with @dlt.expect_all
            for the same expectations.

We reuse the transpiler's emitted SQL for the transform bodies (so the logic is
identical to what the reconcile gate verified) and wrap each layer in the SDP
construct. Expectations are derived from the gold DataSet contract: every
contract column must be non-null (a schema-parity guard that fails loudly at
runtime, mirroring the build-time gate).
"""

from __future__ import annotations

import re
from typing import Any, Dict, List

from . import patterns

# --------------------------------------------------------------------------- #
# Parse the emitted plain-SQL medallion into (view_name, select_body) units.
# The transpiler writes blocks like:
#     CREATE OR REPLACE VIEW <fqn> AS
#     SELECT ...;
_VIEW_RE = re.compile(
    r"CREATE\s+OR\s+REPLACE\s+VIEW\s+([^\s]+)\s+AS\s*(.*?);",
    re.IGNORECASE | re.DOTALL,
)


def _parse_views(sql: str) -> List[Dict[str, str]]:
    out = []
    for m in _VIEW_RE.finditer(sql or ""):
        out.append({"fqn": m.group(1).strip(), "body": m.group(2).strip()})
    return out


def _short(fqn: str) -> str:
    """Last identifier of a dotted FQN → the SDP table name."""
    return fqn.split(".")[-1]


def render(result: Dict[str, Any], language: str = "sql",
           mapping: Dict[str, Any] = None) -> str:
    """Render the transpile `result` as SDP source in `language` ('sql'|'python').

    If `mapping` (an accepted industry-model mapping) is provided, a CONFORMED
    view is appended that projects the gold contract columns to the canonical
    industry-model column names — the governed silver the customer conforms to.
    The parity gold view is untouched (the connector re-point still works).
    """
    if language == "python":
        code = _render_python(result)
    else:
        code = _render_sql(result)
    if mapping and mapping.get("target_table") and mapping.get("columns"):
        code += "\n" + _render_conformed(result, mapping, language)
    return code


def _render_conformed(result: Dict[str, Any], mapping: Dict[str, Any],
                      language: str) -> str:
    """A view projecting gold columns → the canonical industry-model names."""
    st = result.get("structured", {})
    gold_fqn = st.get("gold_view_fqn", "")
    gold_name = _short(gold_fqn) if gold_fqn else "gold"
    target = mapping["target_table"]                     # e.g. customer.party
    conformed = f"{gold_name}_conformed"
    pairs = [(c["domo_column"], c["target_column"])
             for c in mapping["columns"] if c.get("target_column")]
    if not pairs:
        return ""
    if language == "python":
        sel = ",\n            ".join(f"col('{d}').alias('{t}')" for d, t in pairs)
        return (f"# Conformed to industry model {mapping['industry']} · {target}\n"
                f"@dlt.table(comment='Conformed to {target} ({mapping['industry']}).')\n"
                f"def {conformed}():\n"
                f"    return dlt.read('{gold_name}').select(\n            {sel})\n")
    sel = ",\n       ".join(f"`{d}` AS `{t}`" for d, t in pairs)
    return (f"-- Conformed to industry model {mapping['industry']} · {target}\n"
            f"-- Projects the gold contract to canonical {target} column names.\n"
            f"CREATE OR REFRESH MATERIALIZED VIEW {conformed} AS\n"
            f"SELECT {sel}\nFROM {gold_name};\n")


# --------------------------------------------------------------------------- #
# SQL flavor
# --------------------------------------------------------------------------- #
def _render_sql(result: Dict[str, Any]) -> str:
    st = result.get("structured", {})
    bronze = _parse_views(result["sql"].get("bronze", ""))
    silver = _parse_views(result["sql"].get("silver", ""))
    gold = _parse_views(result["sql"].get("gold", ""))
    gold_cols = st.get("gold_schema", [])
    lines: List[str] = [
        "-- Lakeflow Declarative Pipeline (SQL) — generated by Pseudo-Domo.",
        f"-- Source Domo dataflow: {result['lineage']['name']}",
        "-- Bronze = streaming ingest (Auto Loader); silver/gold = materialized views.",
        "",
    ]

    streaming_kw = patterns.tunable("streaming_keyword")
    mv_kw = patterns.tunable("materialized_keyword")
    fmt = patterns.tunable("autoloader_format")

    # Bronze: streaming tables reading raw landing files via Auto Loader.
    for v in bronze:
        name = _short(v["fqn"])
        # The transpiler's bronze body is `SELECT * FROM <catalog>.raw.<src>`.
        src = re.search(r"FROM\s+([^\s;]+)", v["body"], re.IGNORECASE)
        raw = src.group(1) if src else "<raw_source>"
        lines += [
            f"{streaming_kw} {name}",
            f"  COMMENT 'Bronze ingest of {raw} (was a Domo input DataSet).'",
            "AS SELECT * FROM STREAM read_files(",
            f"  '/Volumes/${{catalog}}/${{schema}}/landing/{name}/',",
            f"  format => '{fmt}'",
            ");",
            "",
        ]

    # Silver: one materialized view per transform node.
    for v in silver:
        name = _short(v["fqn"])
        lines += [
            f"{mv_kw} {name} AS",
            _requalify(v["body"]) + ";",
            "",
        ]

    # Gold: materialized view + EXPECT expectations from the DataSet contract.
    for v in gold:
        name = _short(v["fqn"])
        expects = [
            f"  CONSTRAINT valid_{c['name']} EXPECT (`{c['name']}` IS NOT NULL)"
            for c in gold_cols
        ]
        exp_block = " ON VIOLATION DROP ROW,\n".join(expects)
        out_ds = st.get("output_dataset", "")
        lines += [
            f"{mv_kw} {name} ("]
        if exp_block:
            lines.append(exp_block + " ON VIOLATION DROP ROW")
        lines += [
            ")",
            f"  COMMENT 'Gold contract — schema-parity with Domo DataSet {out_ds}.'",
            "AS",
            _requalify(v["body"]) + ";",
            "",
        ]

    # Beast Modes → a Unity Catalog METRIC VIEW (the governed semantic layer),
    # which is the recommended home for card-level metrics on Databricks.
    lines += _metric_view_sql(result)
    return "\n".join(lines)


def _metric_view_sql(result: Dict[str, Any]) -> List[str]:
    st = result.get("structured", {})
    bms = st.get("beast_modes", [])
    if not bms:
        return []
    gold_fqn = st.get("gold_view_fqn", "")
    gold_name = _short(gold_fqn) if gold_fqn else "gold"
    measures = []
    for m in bms:
        note = "" if m["fully_translated"] else "  # REVIEW: partial translation"
        measures.append(
            f"      - name: {m['alias']}\n"
            f"        expr: \"{m['spark_expr']}\"{note}")
    yaml_body = (
        "version: 0.1\n"
        f"source: {gold_name}\n"
        "measures:\n" + "\n".join(measures)
    )
    return [
        "-- ============================================================",
        "-- RECOMMENDED: Unity Catalog METRIC VIEW for the card's Beast Modes.",
        "-- A metric view is the governed semantic layer — define each measure",
        "-- once and reuse it across AI/BI dashboards, Genie, and SQL. This is",
        "-- the recommended home for Domo Beast Modes on Databricks.",
        "-- ============================================================",
        f"CREATE OR REPLACE VIEW {gold_name}_metrics",
        "WITH METRICS",
        "LANGUAGE YAML",
        "AS $$",
        yaml_body,
        "$$;",
        "",
    ]


def _requalify(body: str) -> str:
    """Rewrite fully-qualified upstream view refs to bare SDP table names.

    In an SDP the tables live in one pipeline namespace, so `FROM cat.silver.x`
    becomes `FROM x` (SDP resolves the dependency by name).
    """
    def repl(m):
        return m.group(1) + _short(m.group(2))
    # FROM / JOIN <fqn>
    return re.sub(r"(FROM\s+|JOIN\s+)([a-zA-Z0-9_]+\.[a-zA-Z0-9_.]+)", repl, body)


# --------------------------------------------------------------------------- #
# Python flavor
# --------------------------------------------------------------------------- #
def _render_python(result: Dict[str, Any]) -> str:
    st = result.get("structured", {})
    bronze = _parse_views(result["sql"].get("bronze", ""))
    silver = _parse_views(result["sql"].get("silver", ""))
    gold = _parse_views(result["sql"].get("gold", ""))
    gold_cols = st.get("gold_schema", [])

    out: List[str] = [
        '"""Lakeflow Declarative Pipeline (Python) — generated by Pseudo-Domo.',
        f"Source Domo dataflow: {result['lineage']['name']}",
        '"""',
        "import dlt",
        "from pyspark.sql.functions import *",
        "",
        "catalog = spark.conf.get('catalog', 'main')",
        "schema = spark.conf.get('schema', 'default')",
        "",
    ]

    for v in bronze:
        name = _short(v["fqn"])
        out += [
            "@dlt.table(",
            f"    name='{name}',",
            f"    comment='Bronze ingest (was a Domo input DataSet).')",
            f"def {name}():",
            f"    path = f'/Volumes/{{catalog}}/{{schema}}/landing/{name}/'",
            "    return (spark.readStream.format('cloudFiles')",
            "            .option('cloudFiles.format', 'json').load(path))",
            "",
        ]

    for v in silver:
        name = _short(v["fqn"])
        out += [
            "@dlt.table",
            f"def {name}():",
            f'    return spark.sql("""{_requalify_py(v["body"])}""")',
            "",
        ]

    for v in gold:
        name = _short(v["fqn"])
        exp = {f"valid_{c['name']}": f"{c['name']} IS NOT NULL" for c in gold_cols}
        out += [
            "@dlt.table(",
            f"    comment='Gold contract — schema-parity with Domo DataSet "
            f"{st.get('output_dataset','')}.')",
            f"@dlt.expect_all_or_drop({exp!r})",
            f"def {name}():",
            f'    return spark.sql("""{_requalify_py(v["body"])}""")',
            "",
        ]

    bms = st.get("beast_modes", [])
    if bms and gold:
        gold_name = _short(gold[0]["fqn"])
        out += [
            "# RECOMMENDED: define the card's Beast Modes as a Unity Catalog",
            "# METRIC VIEW (governed semantic layer, reusable across AI/BI +",
            "# Genie). Create it once alongside this pipeline — e.g.:",
            f"#   CREATE VIEW {gold_name}_metrics WITH METRICS LANGUAGE YAML AS $$ ... $$;",
            "# Measures to define:",
        ]
        for m in bms:
            flag = "" if m["fully_translated"] else "   # REVIEW"
            out.append(f"#   - {m['alias']}: {m['spark_expr']}{flag}")
        out.append("")
    return "\n".join(out)


def _requalify_py(body: str) -> str:
    b = _requalify(body)
    return b.replace("\n", "\n           ").strip()
